version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: async_games
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-async_games}
      POSTGRES_USER: ${DB_USERNAME:-async_games}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-async_games}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
